server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDemo01?useunicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mapper:
      mappers:
        - tk.mybatis.mapper.common.Mapper
      notEmpty: true
logging:
  level:
    com.codeing.tabUser.mapper: debug